server:
  port: 6380
spring:
  application:
    name: camellia-redis-proxy-server

camellia-redis-proxy:
  #port: 6380 #The priority is higher than server.port. If it is missing, server.port will be used. If it is set to -6379, a random available port will be used.
  #application-name: camellia-redis-proxy-server # has higher priority than spring.application.name, if missing, use spring.application.name
  console-port: 16379 #console port, the default is 16379, if set to -16379, there will be a random available port, if set to 0, the console will not be started
  password: pass123 #proxy password, if a custom client-auth-provider-class-name is set, the password parameter is invalid
  monitor-enable: false #Whether to enable monitoring
  monitor-interval-seconds: 60 #Monitor callback interval
  plugins: #
    - monitorPlugin
    - bigKeyPlugin
    - hotKeyPlugin
  transpond:
    type: local #Use local configuration
    local:
      type: simple
      resource: redis://@127.0.0.1:6379 #Forwarded redis address
#      resource: redis-sentinel://@127.0.0.1:26379/master1
#      resource: redis-sentinel-slaves://@127.0.0.1:26379/master1
#      resource: redis-cluster://@nim-redis-perftest-jd-1.v1.yunxin.jd1.vpc:7000,nim-redis-perftest-jd-2.v1.yunxin.jd1.vpc:7006, nim-redis-perftest-jd-3.v1.yunxin.jd1.vpc:7010
#      type: complex
#      json-file: resource-table.json
#    redis-conf:
#      multi-write-mode: first_resource_only #Double write mode, by default the first address will be returned
#      close-idle-connection: true #Whether to close idle connections, the default is true
#      check-idle-connection-threshold-seconds: 600 #How long to count an idle connection, the default is 600s
#      preheat: true #Preheat switch


camellia-redis-zk-registry:
  enable: false #Register to zk
  zk-url: 127.0.0.1:2181 #zk address
  base-path: /camellia #registered to the base-path of zk

camellia-redis-proxy-nacos:
  enable: false #Whether to get the configuration file from nacos
  server-addr: 127.0.0.1:8848 #nacos address
  nacos-conf: #Other nacos configuration items
    k1: v1
    k2: v2
  conf-file-list:
    - file-name: camellia-redis-proxy.properties #file name
      data-id: camellia-redis-proxy.properties #nacos dataId
      group: camellia #nacos' group
    - file-name: logback.xml #file name
      data-id: logback.xml
      group: camellia